[workspace]
resolver = "3"
members = ["server", "client", "chat_lib"]

[workspace.dependencies]
serde = { version= "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
tokio = { version = "1.37", features = ["full"] }
anyhow = "1.0.98"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
